import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="bg-neutral-100 h-screen w-screen overflow-hidden flex flex-row">
          <div className="flex flex-col flex-1">{children}</div>
        </div>
      </body>
    </html>
  );
}
